### ISSUE TITLE
i7-8565U CPU+GPU Performance Issues

### ISSUE THREAD

**Issue by tvieira20** [Jie2GG/Hackintosh-ASUS-S5300FN#12]
Hi,
I'm opening this "Issue" to know if this is getting updated, as the latest update this repo had was 4 months ago.
Also, I'm having LaunchPad and other graphical fps drops randomly. I tested with Intel Power Gadget GPU Max frequency and CPU Max Frequency and things get odd:

Here is CPU Max Frequency Test - After a few seconds CPU Steps the Frequency down for some reason
<img width="463" alt="Captura de ecrã 2021-01-10, às 19 01 57" src="https://user-images.githubusercontent.com/55699311/104132783-6a9fc000-5377-11eb-8834-643ef52f77e6.png">

Here is GPU Max Frequency Test - Same thing as CPU test: GFX Frequency steps down
<img width="587" alt="Captura de ecrã 2021-01-10, às 19 05 13" src="https://user-images.githubusercontent.com/55699311/104132819-9d49b880-5377-11eb-97f5-068b1b9ebddb.png">

Tried a clean install, kext update, HiDPI on/off (there's a FPS increase with no HiDPI).
Also tried MacBook Air 8,2 instead of the MacBook Pro 15,4 - and system got a bit more stable, faster shutdowns, better overall response. 
What can I do?

macOS 11.1 , VivoBook S530Fn // i7-8565U
Thanks

**Comment by Jie2GG** [comment]
I’m using MacBook Pro16,3

**Comment by tvieira20** [comment]
I replaced the EFI you updated. CPU now is at 4,2GHz Max Frequency instead of the 4.6GHz.. Same issue persists: CPU Core steps down randomly 
![Captura de ecrã 2021-01-11, às 14 32 24](https://user-images.githubusercontent.com/55699311/104195159-2b767b00-541a-11eb-9238-4088336cd0de.png)

Tried to generate a new CPUFriend kext. Nothing changed
Anything else I can try?

**Comment by Jie2GG** [comment]
Did you create your CPUFriend from a MacBook Air8,2 model?

**Comment by tvieira20** [comment]
No. I created it from MacBook Pro 16.3

**Comment by Jie2GG** [comment]
> No. I created it from MacBook Pro 16.3
> […](#)
> No dia 11/01/2021, às 14:51, Jie2GG ***@***.***> escreveu: ﻿ Did you create your CPUFriend from a MacBook Air8,2 model? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Give it a try MacBook Air8,2 ？

**Comment by Jie2GG** [comment]
@tvieira20  Hello, Your CPU frequency should have something to do with module. My CPU is Intel Core I5 8265U, max frequency in 3.9GHz, but your CPU is Intel Core I7 8565U, perhaps your can using other module to process this issues.

**Comment by tvieira20** [comment]
> @tvieira20 Hello, Your CPU frequency should have something to do with module. My CPU is Intel Core I5 8265U, max frequency in 3.9GHz, but your CPU is Intel Core I7 8565U, perhaps your can using other module to process this issues.

What do you mean "using another module to process this issues"?

Also, MacBook Air 8,2 didn't do anything performance-wise

**Comment by Jie2GG** [comment]
Sorry, my English is not good. 
My mean is “MacBook Air 8,2”, use CPU in i5 8210Y. close to i5 8265U. but your CPU in i7 8565U, should use close to laptop model.

**Comment by tvieira20** [comment]
> Sorry, my English is not good.
> My mean is “MacBook Air 8,2”, use CPU in i5 8210Y. close to i5 8265U. but your CPU in i7 8565U, should use close to laptop model.

Not problem, I'm thankful you're helping me out.
I went back to MacBook Pro 16,3 as it was giving me better performance with this 0.6.4 EFI.
This time CPU Frequency was 4.2GHz (instead of 4.6GHz Max) and 1.2GHz instead of 800MHz (Turbo Step down) so I generated a new CPU Friend using CPU Friend One Key. I'll see if it works better now.
Thanks
<img width="774" alt="Captura de ecrã 2021-01-12, às 12 47 54" src="https://user-images.githubusercontent.com/55699311/104316681-be73eb80-54d4-11eb-8815-9fbcf307be87.png">
<img width="703" alt="Captura de ecrã 2021-01-12, às 12 44 21" src="https://user-images.githubusercontent.com/55699311/104316689-c3389f80-54d4-11eb-9c20-f6061ba7cdf6.png">

**Comment by Jie2GG** [comment]
I very happy can give you helping. 
It seems this CPU need CPUFriend to improve stability.

**Comment by tvieira20** [comment]
> I very happy can give you helping.
> It seems this CPU need CPUFriend to improve stability.

Mate I sorted it out... **Turns out that CPUFriend was DISABLED in config.plist** - OpenCore 
Now I get 4.6GHz Turbo (finally) and decent GPU Performance/Stability
Also got a better Idle Clock Speeds.

Here's some prints:
CPU Max Frequency:

<img width="512" alt="Captura de ecrã 2021-01-12, às 13 00 07" src="https://user-images.githubusercontent.com/55699311/104318622-9043db00-54d7-11eb-9308-4dec2288c832.png">



GPU Max Frequency: (although looks the same: now the Power doesn't cut after a few seconds like it did previously)
<img width="512" alt="GPU TEST" src="https://user-images.githubusercontent.com/55699311/104318488-64c0f080-54d7-11eb-88ce-6b1758c69180.png">

Idle:
<img width="468" alt="IDLE" src="https://user-images.githubusercontent.com/55699311/104318504-6ab6d180-54d7-11eb-9e5b-36bec674413c.png">

Thanks again for helping me out!

**Comment by Jie2GG** [comment]
It was a mutual help process, and you helped me solve some problems.

**Comment by Jie2GG** [comment]
@tvieira20 My friend, I unlocked the BIOS CFG Lock to get more stable CPU performance, if you need to unlock CFG Lock can follow my tutorial. But there are risks.
