### ISSUE TITLE
i7-8565U怎么修改可以正常使用

### ISSUE THREAD

**Issue by ChuJian2** [Jie2GG/Hackintosh-ASUS-S5300FN#16]
您好，我与您是同型号的，其他全部一样，只有CPU是i7-8565U，使用您的EFI无法正常启动、看到前面说稍作修改可以使用，请问该怎么修改呀。

**Comment by Jie2GG** [comment]
请了解 OpenCore、DSDT和SSDT 等相关知识后修改.

**Comment by ChuJian2** [comment]
好的。

**Comment by ChuJian2** [comment]
我自己改了但还是一直不成功，请问我可以加您的QQ之类的详细请教一下吗？有偿。
