### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by boromyr** [Jie2GG/Hackintosh-ASUS-S5300FN#17]
Hi, I'm trying to use your efi to boot the macos 11 installation, but after booting from OpenCore I get a notification sound, and immediately after that Windows 10 is started without being able to choose other options. I actually only managed to boot once OC by quickly pressing keys to stop the boot timeout, but I can't even do it that way anymore, I must have just gotten lucky.
How can I disable the startup timeout?
Thank you.

**Comment by Jie2GG** [comment]
Sorry, unable helper in your. My EFI files boot macOS BigSur Installation no issues.

**Comment by boromyr** [comment]
I used it to start installing BigSur. I can confirm it because I managed to launch bigsur only once. My problem I believe it is in the automatic boot, with the classic message "Press a key within 5 seconds to cancel <something>", it seems that in my case it is set to 0.
Have you enabled the boot timeout in your EFI? If yes, I would like to disable it.

**Comment by Jie2GG** [comment]
No, I not enable seting boot timeout. can you give me hardware infomaction ? (include BIOS Version)

**Comment by boromyr** [comment]
The PC model is obviously S530FN. The BIOS is 308. All the other components are the original ones, I only added a ram in the second slot. Fast boot deactivated.

**Comment by Jie2GG** [comment]
Your notebook Wireless Network Card is Intel Wireless ?

**Comment by boromyr** [comment]
I think so, I have not replaced anything from the original hardware. I also tried the MacOS 12 version and also Catalina, downloaded from the Hackintosh forum. I also tried to insert your EFI into the system "EFI" system, recorded as a second boot, and started without any MacOS or USB support inserted. Also in this case upload Windows directly. In fact now I write to you with Windows started with your EFI.

**Comment by Jie2GG** [comment]
Please setting Intel Wireless is Disable. Then booting macOS installation.

**Comment by boromyr** [comment]
Do you mean by the BIOS right?

**Comment by Jie2GG** [comment]
Yes, Go to BIOS

**Comment by boromyr** [comment]
OK thank you very much!
