### ISSUE TITLE
安装过程中出现了禁止符号

### ISSUE THREAD

**Issue by wjhwh** [Jie2GG/Hackintosh-ASUS-S5300FN#2]
你好 我在安装过程中出现了禁止符号需要怎么解决呢

**Comment by Jie2GG** [comment]
在文件中打开 -v 看看是在哪里出现的禁止符号.

**Comment by wjhwh** [comment]
谢谢 我装好了 你的那个触摸驱动好像用不了 声音也不能用按键解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jie2GG"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 上午10:55
收件人:&nbsp;"Jie2GG/Hackintosh-ASUS-S5300FN"<Hackintosh-ASUS-S5300FN@noreply.github.com&gt;;
抄送:&nbsp;"2010367502"<2010367502@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Jie2GG/Hackintosh-ASUS-S5300FN] 安装过程中出现了禁止符号 (#2)




在文件中打开 -v 看看是在哪里出现的禁止符号.

**Comment by Jie2GG** [comment]
> 谢谢我装好了你的那个触摸驱动好像用不了声音也不能用按键解决
> […](#)
> “2010367502”<2010367502@qq.com>；；“Author”<author@noreply.github.com>；；主题： ；Re：[Jie2GG/黑金托什-ASUS-S5300FN]安装过程中出现了禁止符号(#2)在文件中打开-v.看看是在哪里出现的禁止符号.-你收到这封信是因为你写了这条线。直接回复这封电子邮件，在GitHub上查看，或者取消订阅。

 触控板需要在添加 DSDT之前就需要驱动好。即添加 DSDT.aml 之前， 触控板应处于能使用的状态。才可以添加DSDT
