### ISSUE TITLE
S5300UN完美运行10.14.6

### ISSUE THREAD

**Issue by lang-v** [Jie2GG/Hackintosh-ASUS-S5300FN#4]
基本正常，over，谢谢大佬，tql。
蓝牙好像有点小问题，第一次打开的时候能够正常使用，甚至还能用来共享网络，重启之后就没了。不过我很少不用蓝牙。
安装10.15.3的时候会出现找不到硬盘的情况，我不知道自己是怎么弄的，（10.15.3）第一次成功装了进去，触摸板好像没有10.14.6的舒服，后来我重装就再也装不回去了，一直找不到我的硬盘。
装10.14.6很顺利，不会找不到硬盘，就遇到一个时间问题，修改时间就OK了。
再次谢谢大佬😁。

**Comment by Jie2GG** [comment]
你用的是 CLOVER 还是 OPENCORE

**Comment by lang-v** [comment]
clover

**Comment by lang-v** [comment]
> 你用的是 CLOVER 还是 OPENCORE

clover，我搞快了，才想起来还有些功能还没试过，我马上试试

**Comment by Jie2GG** [comment]
> > 你用的是 CLOVER 还是 OPENCORE
> 
> clover，我搞快了，才想起来还有些功能还没试过，我马上试试

请使用 OPENCORE, CLOVER 我已经不维护了

**Comment by lang-v** [comment]
> > > 你用的是 CLOVER 还是 OPENCORE
> > 
> > 
> > clover，我搞快了，才想起来还有些功能还没试过，我马上试试
> 
> 请使用 OPENCORE, CLOVER 我已经不维护了

好的，哥。
