### ISSUE TITLE
ASUS VivoBook S530Fn - iGPU Performance Issues + HDMI Fix

### ISSUE THREAD

**Issue by tvieira20** [Jie2GG/Hackintosh-ASUS-S5300FN#5]
Hi. I had macOS Mojave 10.14.6 on my ASUS VivoBook S530Fn (i7-8565U, 8GB RAM, UHD620+NVIDIA MX150, 2 SSDs, BCM4352Z for Wi-Fi and BT) and at the time I patched the Intel UHD 620 to UHD 630 because that was the only Device ID that was working at the time and the iGPU Performance was pretty similar with Windows 10.  SMBIOS was set to MacBook Pro 15,2.

**Geekbench 4 UHD 620 Test (OpenCL):**

- Windows 10: 28295  -- [https://browser.geekbench.com/v4/compute/4039947](url)
- macOS Mojave: 26148  --  [https://browser.geekbench.com/v4/compute/3980724](url)

Now using your EFI in macOS Catalina 10.15.4 [SMBIOS=MacBook Pro 15,4 // iGPU ID Set to 'Intel Iris Plus Graphics 655'] it scores 17425 [https://browser.geekbench.com/v4/compute/4773367](url) . 
Performance on Windows 10 is around 28000 still.

Shoudn't the patch be set to UHD 630 since it gets more performance of the Intel GPU?

Also, the CPU Performance in 1-Core can't get past 4200MHz instead of the 4600MHz that it can handle (which is why the CPU Bench in Catalina is also very low comparing with Win10). Is that a Power Management Issue?

**Geekbench 4 i7-8565U Test (64-bit):**

- Windows 10: Single Core: **5163**  | Multi Core: **14205** -- [https://browser.geekbench.com/v4/cpu/13203473](url)
- macOS Catalina: Single Core: **4788** | Multi Core: **11668** --  [https://browser.geekbench.com/v4/cpu/15360005](url)

Thanks for everything

**Comment by Jie2GG** [comment]
Thanks for your feedback

When I set my iGPU to "Intel iris 655", my HDMI works well at 2K / 4K resolution.
But I didn't know it was bring a performance issue. 
When I try to set it to “UHD”630, the HDMI output 2K / 4K resolution will a flower screen appears. 
Lead to can’t using HiDPI resolution.

so I proposal your should first test HDMI output is normal working. My also will test my iGPU work frequency is it normal. 

Thanks again for your feedback

**Comment by tvieira20** [comment]
Hi. When I plug an HDMI Cable into the Port the Laptop Reboots. It reboots each time I connect the HDMI Cable and even if I boot with the HDMI Cable inserted it doesn't recognize anything (it's like there's no cable attached at all).  I tried to boot with the HDMI Cable inserted and went to Hackintool to see if the System was detecting the Cable and it wasn't showing up.
<img width="1440" alt="Captura de ecrã 2020-04-02, às 16 35 47" src="https://user-images.githubusercontent.com/55699311/78269533-a0b73600-7501-11ea-987f-4d0cedf5d920.png">

Also, I forgot to mention 2 things: that the screen sometimes shows these wierd lines in Telegram App. It doesn't happen in Linux or in Windows 10.
![photo_2020-04-02 16 49 08](https://user-images.githubusercontent.com/55699311/78269826-00154600-7502-11ea-9083-87ff0cda1525.jpeg)
And that the F6/F7 keybindings to control the keyboard led's don't work but the led's themselves are always lit. I tried to remap them using Karabiner (since I use it to remap some missing buttons on PT-PT keyboards) and it's showing this:
<img width="1440" alt="Captura de ecrã 2020-04-02, às 16 52 38" src="https://user-images.githubusercontent.com/55699311/78270251-7e71e800-7502-11ea-938a-2c8d59eb304f.png">
<img width="1112" alt="Captura de ecrã 2020-04-02, às 16 52 43" src="https://user-images.githubusercontent.com/55699311/78270321-93e71200-7502-11ea-9185-0584cebeba08.png">
<img width="1112" alt="Captura de ecrã 2020-04-02, às 16 52 47" src="https://user-images.githubusercontent.com/55699311/78270326-95183f00-7502-11ea-8097-80774e5acc21.png">

Any help would be appreciated. Thanks once again for all your work 😊 

EDIT 1: i noticed i had some kexts that weren't updated. I'll update them and see if it gets the thing going 
<img width="1440" alt="Captura de ecrã 2020-04-02, às 17 01 29" src="https://user-images.githubusercontent.com/55699311/78271130-b4639c00-7503-11ea-88f5-97d3a5e63c3d.png">
EDIT 2: every kext it fully updated and I can't control the Keyboard LED's. I tried to uninstall Karabiner to see it would help but it's still not working. It's strange because a few days ago it was working and  Yesterday when I booted it up in the morning i couldn't control them
<img width="1440" alt="Captura de ecrã 2020-04-02, às 17 30 35" src="https://user-images.githubusercontent.com/55699311/78274406-132b1480-7508-11ea-9219-78ec94213e13.png">

**Comment by Jie2GG** [comment]
### Hello, I have looked at your problem and suggested the following solution

**Question**
Your HDMI is not working of Notebook

**Solution**
Because our notebook models are similar. I think your computer HDMI interface located ‘index: 2’ (0x06 of physical port). so, your can set the “busID” of index 2 to 0x02 and set the “Type” of index 2 to HDMI in Hackintool.
As shown in the following figure.
![Hackintool](https://github.com/Jie2GG/Hackintosh-ASUS-S5300FN/blob/Other/pic1.png?raw=true)

##
**Question**
Your Fn+F6/F7 Unable to adjust keyboard led of Notebook

**Solution**
Your need to use ‘AsusSMC.kext’ and ‘SSDT-AsusSMC.aml’ to modify the keyboard mapping **(It doesn’t work perfectly on Catalina)**. These files exist in my EFI. At the same time, in order to make SSDT effective. your must refer to my ‘config.plist’. Add the corresponding patch to your config. 

#### PS: Before using ‘SSDT-AsusSMC.aml’, you need to undo the changes to the keyboard backlight in the DSDT.

```
Comment:  Rename _Q0D to XQ0D
Find:     5F513044
Replace:  58513044

Comment:  Rename _Q0E to XQ0E
Find:     5F513045 
Replace:  58513045 

Comment:  Rename _Q0F to XQ0F
Find:     5F513046 
Replace:  58513046 

Comment:  Rename _Q12 to XQ12
Find:     5F513132 
Replace:  58513132 
```

**Comment by tvieira20** [comment]
Hi. I only got the Laptop with me since yesterday.

The Keyboard Backlight started working again using Fn+F6 and Fn+F7 [Decrease / Increase] and required 0 workarounds - I guess it was due to some old kext version...
Regarding the HDMI:  I tried what you advised me (switching Port Index 2 to "HDMI") 
<img width="1049" alt="Captura de ecrã 2020-05-11, às 14 15 07" src="https://user-images.githubusercontent.com/55699311/81567626-770cec80-9394-11ea-9b21-77da6a57f17c.png">
<img width="1424" alt="Captura de ecrã 2020-05-11, às 13 20 24" src="https://user-images.githubusercontent.com/55699311/81567645-7ecc9100-9394-11ea-8568-0bcb36c1fec0.png">

and I removed some options to make it not reboot after HDMI Cable plugged in using Hackintool:
- Disabled "VRAM 2048MB" + "Enable HDMI20 (4K)" - I don't use 4K External Display

By doing so now the Laptop won't reboot each time I try to plug the HDMI Cable... But now theres something good: the External Monitor now detects that there's something connected but theres still **no HDMI Output to my External Monitor**...
Video [https://streamable.com/2mvwls](url)
Anything else I can try here? Thanks for everything

**Comment by Jie2GG** [comment]
Regarding the HDMI interface not working:

1. using model “MacBookPro 15,2” or “MacBookPro 15,4” (I recommend the latter) in Laptop
2. Change the “BusId” of Index2 Port to 0x02 and type of HDMI

Regarding other the “FrameBuffer” some advices on patch :

* Advanced

    - [ ] DVMT pre-alloc 32MB
    - [ ] Disable eGPU ( using “SSDT-DisableGPU”  cut off the power of GPU)
    - [ ] DP -> HDMI 
    - [ ] Use Intel HDMI
    - [ ] Hotplug Reboot Fix
    - [x] HDMI Infinite Loop Fix
    - [ ] Spoof Audio Device ID
    - [ ] VRAM 2048MB
    - [x] Enable HDMI20 (4K)
    - [ ] GfxYTile Fix
    - [ ] USB Port Limit
    - [ ] DPCD Max Link Rate
    - [ ] Framebuffer Port Limit
    - [ ] Inject Fake IGPU

* LSPCON
    OFF, Laptop not support device

Let me explain why:
    1. Laptop of HDMI port is 1.4 protocol, unable using 4K@60Hz. but “HDMI Infinite Loop Fix” + “Enable HDMI20 (4K)” can Enable 4K@50Hz output, so I recommend.
    2. using 0x3EA50009 in iGPU, can solve HiDPI error display.

**Comment by tvieira20** [comment]
> Regarding the HDMI interface not working:
> 
> 1. using model “MacBookPro 15,2” or “MacBookPro 15,4” (I recommend the latter) in Laptop
> 2. Change the “BusId” of Index2 Port to 0x02 and type of HDMI
> 
> Regarding other the “FrameBuffer” some advices on patch :
> 
> * Advanced
>   
>   * [ ]  DVMT pre-alloc 32MB
>   * [ ]  Disable eGPU ( using “SSDT-DisableGPU”  cut off the power of GPU)
>   * [ ]  DP -> HDMI
>   * [ ]  Use Intel HDMI
>   * [ ]  Hotplug Reboot Fix
>   * [x]  HDMI Infinite Loop Fix
>   * [ ]  Spoof Audio Device ID
>   * [ ]  VRAM 2048MB
>   * [x]  Enable HDMI20 (4K)
>   * [ ]  GfxYTile Fix
>   * [ ]  USB Port Limit
>   * [ ]  DPCD Max Link Rate
>   * [ ]  Framebuffer Port Limit
>   * [ ]  Inject Fake IGPU
> * LSPCON
>   OFF, Laptop not support device
> 
> Let me explain why:
> 1. Laptop of HDMI port is 1.4 protocol, unable using 4K@60Hz. but “HDMI Infinite Loop Fix” + “Enable HDMI20 (4K)” can Enable 4K@50Hz output, so I recommend.
> 2. using 0x3EA50009 in iGPU, can solve HiDPI error display.

Thanks! It's finally working!!!
I forgot to change Busid to 0x02 and once I plugged in HDMI Cable it started to appear in System Information as NVIDIA (meaning it was pointing at Disabled MX150). 
<img width="983" alt="Captura de ecrã 2020-05-11, às 16 51 44" src="https://user-images.githubusercontent.com/55699311/81584678-f6a5b600-93aa-11ea-992a-4d345cb1d11d.png">
<img width="983" alt="Captura de ecrã 2020-05-11, às 16 51 56" src="https://user-images.githubusercontent.com/55699311/81584693-fa393d00-93aa-11ea-87a8-4f86ee2c536c.png">
<img width="852" alt="Captura de ecrã 2020-05-11, às 16 52 14" src="https://user-images.githubusercontent.com/55699311/81584696-fb6a6a00-93aa-11ea-8501-be07871522cf.png">

Once I sorted it out I got it working (except that Magenta Color which I'm about to fix next using Forced RGB Mode/EDID Patch)
![IMG_0287](https://user-images.githubusercontent.com/55699311/81584809-28b71800-93ab-11ea-8488-f3b45e9d1b42.jpg)

Screenshots of Everything Working:
<img width="1424" alt="Captura de ecrã 2020-05-11, às 17 09 05" src="https://user-images.githubusercontent.com/55699311/81584913-4edcb800-93ab-11ea-84a0-37a615b4d55b.png">
![Captura de ecrã 2020-05-11, às 17 09 05 (2)](https://user-images.githubusercontent.com/55699311/81584931-54d29900-93ab-11ea-8b02-b32cca946963.png)
Once again, thank you for everything

**Comment by tvieira20** [comment]
Final Picture of Everything Working:

![IMG_C91F0BD55C55-1](https://user-images.githubusercontent.com/55699311/81589581-72a2fc80-93b1-11ea-85e1-9377c71152b9.jpeg)

@Jie2GG You can add to the "Working List" the following: Instant Hotspot, Handoff, Universal Clipboard, AirDrop and Apple Watch Unlocking. They've been working without issues on my side for over 3 months 😉

**Comment by Jie2GG** [comment]
> Final Picture of Everything Working:
> 
> ![IMG_C91F0BD55C55-1](https://user-images.githubusercontent.com/55699311/81589581-72a2fc80-93b1-11ea-85e1-9377c71152b9.jpeg)
> 
> @Jie2GG You can add to the "Working List" the following: Instant Hotspot, Handoff, Universal Clipboard, AirDrop and Apple Watch Unlocking. They've been working without issues on my side for over 3 months 😉

Your can using “SSDT-OffGPU” GPU of power off, ACPI file in my EFI.
