### ISSUE TITLE
Reboot when connecting HDMI on UHD 620 Catalina 10.15.5

### ISSUE THREAD

**Issue by orcoliver** [Jie2GG/Hackintosh-ASUS-S5300FN#6]
Hi, do you fix the HDMI on catalina 10.15.5?

**Comment by Jie2GG** [comment]
Please use old graphics driver of 10.15.4.

Replace the driver in S/L/E and rebuild the cache.

[Graphics of Catalina 10.15.4.zip](https://github.com/Jie2GG/Hackintosh-ASUS-S5300FN/files/4798805/Graphics.of.Catalina.10.15.4.zip)

**Comment by orcoliver** [comment]
Thks!
