### ISSUE TITLE
Can't install Big Sur

### ISSUE THREAD

**Issue by congtuan0104** [Jie2GG/Hackintosh-ASUS-S5300FN#7]
Hi, I've got a laptop with similar specs to yours and while I got Catalina 10.15.6 running fine but  I can't install Big Sur beta 2 Although I have updated kext and OC 0.6.0, download Big Sur image from Olarila and copy your EFI to USB. 
Please fix it. (Thank you Bro.)

**Comment by Jie2GG** [comment]
branches macOS-11.0 can install macOS 11.0 bate3 and update macOS 11.0 bate4, but OpenCore is not new last version

**Comment by congtuan0104** [comment]
Oh, thank you very much.

**Comment by congtuan0104** [comment]
I tried to use that but the computer always reboot after running here
![117527096_335211037853529_3903500415921602741_n](https://user-images.githubusercontent.com/57316900/89667351-3165ae80-d906-11ea-82ea-8b1e099f0a7f.jpg)

**Comment by Jie2GG** [comment]
Please attach your computer's hardware configuration like reademe.md

**Comment by Jie2GG** [comment]
> I tried to use that but the computer always reboot after running here
> ![117527096_335211037853529_3903500415921602741_n](https://user-images.githubusercontent.com/57316900/89667351-3165ae80-d906-11ea-82ea-8b1e099f0a7f.jpg)

This picture does not yield useful information

**Comment by congtuan0104** [comment]
My laptop is ASUS Vivobook S15 S530FN
CPU: Intel Core i5 8265U
Mainboard: X530FN_S5300FN
RAM: 12GB (8GB Kingston + 4GB 04CB)
SSD: CT250MX500SSD4 250GB
HDD: TOSHIBA MQ04ABF100 1TB
Wifi: Intel AC 8265
GPU: Intel UHD620 + MX150

**Comment by Jie2GG** [comment]
Please use this EFI booting macOS 11.0 install volume.

This EFI is the one I'm using

[EFI.zip](https://github.com/Jie2GG/Hackintosh-ASUS-S5300FN/files/5044622/EFI.zip)

**Comment by congtuan0104** [comment]
Thank you, it works perfectly.

**Comment by Jie2GG** [comment]
> Thank you, it works perfectly.

Please replace config “SystemSerialNumber”, “SystemUUID”, “MLB” and “ROM” for your random value

**Comment by congtuan0104** [comment]
I replaced it as soon as I got into macOS.

**Comment by Jie2GG** [comment]
> I replaced it as soon as I got into macOS.

OK, Thank you.
